language: smalltalk
sudo: false
addons:
    apt:
        packages:
            - libssl1.0.0:i386
smalltalk:
    - Pharo-alpha
    - Pharo-stable
    - Pharo-5.0
    - Pharo-4.0
    - Pharo-3.0
env:
    global:
        - BASELINE="Whatever"
        - TESTS="Whatever"
        - PACKAGES="/repository"
        - BASELINE_GROUP="default"
