language: smalltalk
sudo: false
addons:
    apt:
        packages:
            - libssl1.0.0:i386
smalltalk:
    - Pharo-5.0
after_failure:
    - $PHARO_VM --nodisplay "$SMALLTALK_CI_BUILD/$PHARO_IMAGE" test --junit-xml-output --fail-on-failure "$TESTS" 2>&1
env:
    global:
        - BASELINE="Whatever"
        - TESTS="Whatever"
        - PACKAGES="/repository"
        - BASELINE_GROUP="default"
